# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box          = "windows_10"
  config.vm.communicator = "winrm"

  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = true
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
      v.enable_vmrun_ip_lookup = false
      v.linked_clone = true
      v.vmx["usb.present"] = "TRUE"
      v.vmx["usb_xhci.present"] = "TRUE"
      v.vmx["usb.generic.pluginAction"] = "guest"
    end
  end

  config.vm.define "recuva" do |config|
    config.vm.provision "shell", path: "scripts/install-chocolatey.ps1", privileged: false
    config.vm.provision "shell", path: "scripts/install-recuva.ps1", privileged: false
  end
end
