# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$script = <<PS1
iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
choco install anyvideoconverter
PS1

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "lmayorga1980/windows7-sp1"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 1024
    vb.cpus = 2
    vb.customize ["modifyvm", :id, '--audio', 'coreaudio', '--audiocontroller', 'hda'] # choices: hda sb16 ac97
  end

  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = true
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "2"
      v.vmx["sound.startconnected"] = "TRUE"
      v.vmx["sound.present"] = "TRUE"
      v.vmx["sound.autodetect"] = "TRUE"
    end
  end

  config.vm.provision "shell", inline: $script

end
