# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu1204x64-desktop"
  config.vm.box_url = "file:///e:/basebox/ubuntu1204x64-desktop.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.131", gateway: "192.168.33.1"

  config.vm.provision "shell", path: "shell/install-tools.sh"
  config.vm.hostname = "vagrant-ubuntu1204"

 
   config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
     vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
     vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
   end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

end
