# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # the Jenkins CI server
  config.vm.define "ci", primary: true do |ci|
    ci.vm.box = "precise64"
    ci.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
    ci.vm.hostname = "ci"
    ci.vm.network :private_network, ip: "196.168.33.214"
    ci.vm.network :forwarded_port, guest: 8080, host: 8080
  
    ci.vm.provision "shell", privileged: false, path: "scripts/install-jenkins-server.sh"
  
    ci.vm.provider :virtualbox do |vb|
      # Use VBoxManage to customize the VM. For example to change memory:
      vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "1"]
    end
  end

  # the Windows 2008 R2 Jenkins slave
  config.vm.define "slave1", primary: true do |slave1|
    slave1.vm.box = "win2008R2-datacenter-eval"
#    slave1.vm.box_url = "file:///e:/basebox/win2008R2-datacenter-eval.box"
    slave1.vm.box_url = "file:///g:/GitHub/basebox-packer/virtualbox/win2008R2-datacenter-eval.box"

    slave1.vm.guest = :windows
    slave1.windows.halt_timeout = 25
    slave1.vm.boot_timeout = 120
    slave1.winrm.username = "vagrant"
    slave1.winrm.password = "vagrant"

    slave1.vm.network :private_network, ip: "192.168.33.215", gateway: "192.168.33.1"
    slave1.winrm.port = 50859
    slave1.vm.network :forwarded_port, guest: 5985, host: 50859

    slave1.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "768", "--cpus", "1"]
    end
  
    slave1.vm.provision "shell", path: "scripts/install-jenkins-slave.bat"
  end

end
