# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # the Jenkins CI server
  config.vm.define "ci", primary: true do |ci|
    ci.vm.box = "precise64"
    ci.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
    ci.vm.hostname = "ci"
    ci.vm.network :private_network, ip: "192.168.33.214"
#    ci.vm.network :forwarded_port, guest: 8080, host: 8080
  
    ci.vm.provision "shell", privileged: false, path: "scripts/install-jenkins-server.sh"
  
    ci.vm.provider :virtualbox do |vb|
      # Use VBoxManage to customize the VM. For example to change memory:
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    end
  end

  # the Windows 2012 R2 Jenkins slave1
  config.vm.define "slave1", primary: true do |slave1|
    slave1.vm.box = "windows_2012_r2"

    slave1.vm.guest = :windows
    slave1.vm.hostname = "slave1"

    slave1.vm.network :private_network, ip: "192.168.33.215", gateway: "192.168.33.1"
    slave1.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    slave1.windows.set_work_network = true

    slave1.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1680x1024x32"]
    end
  
    slave1.vm.provision "shell", path: "scripts/install-jenkins-slave.bat"
    slave1.vm.provision "shell", path: "scripts/reboot-to-slave.bat"
  end


  # the Ubuntu Jenkins slave2
  config.vm.define "slave2", primary: true do |slave2|
    slave2.vm.box     = "precise64"
    slave2.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
    slave2.vm.hostname = "slave2"
    slave2.vm.network :private_network, ip: "192.168.33.216"
  
    slave2.vm.provision "shell", privileged: false, path: "scripts/install-jenkins-slave.sh"
  
    slave2.vm.provider :virtualbox do |vb|
      # Use VBoxManage to customize the VM. For example to change memory:
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
    end
  end


  # the Windows 2008 R2 Jenkins slave3
  config.vm.define "slave3", primary: true do |slave3|
    slave3.vm.box = "windows_2008_r2"

    slave3.vm.guest = :windows
    slave3.vm.hostname = "slave3"

    slave3.vm.network :private_network, ip: "192.168.33.217", gateway: "192.168.33.1"
    slave3.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    slave3.windows.set_work_network = true

    slave3.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1680x1024x32"]
    end
  
    slave3.vm.provision "shell", path: "scripts/install-jenkins-slave.bat"
    slave3.vm.provision "shell", path: "scripts/reboot-to-slave.bat"
  end


end
