# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "win2008R2-datacenter-eval"
  config.vm.box_url = "file:///e:/basebox/win2008R2-datacenter-eval.box"
  config.vm.guest = :windows
  config.windows.halt_timeout = 25

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.port = 59882

  config.vm.network :forwarded_port, guest: 5985, host: 59882
  config.vm.network :private_network, ip: "192.168.33.82", gateway: "192.168.33.1"
 
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
  end

  # Enable provisioning with a PowerShell script
  config.vm.provision "shell", path: "shell/main.cmd"
    
end
