Vagrant.configure("2") do |config|

  config.vm.define "linux" do |config|
    config.vm.hostname = "linux"
    config.vm.box      = "tknerr/ubuntu1604-desktop"

    ["vmware_fusion", "vmware_workstation"].each do |provider|
      config.vm.provider provider do |v, override|
        v.gui                    = true
        v.memory                 = 4096
        v.cpus                   = 2
        v.enable_vmrun_ip_lookup = false
        v.linked_clone           = true
        v.vmx["vhv.enable"]      = "TRUE"
        v.ssh_info_public        = true
      end
    end

    config.vm.provision "shell", inline: <<-SHELL
      if [ ! -f .done ]; then
        apt-get update
        wget --no-verbose https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb
        sudo dpkg -i vagrant*.deb
        wget --no-verbose http://download3.vmware.com/software/wkst/file/VMware-Workstation-Full-14.1.1-7528167.x86_64.bundle
        sudo sh ./VMware-Workstation-Full*.bundle --console --required --eulas-agreed
        touch .done
      fi
      vagrant plugin install vagrant-vmware-workstation --plugin-version 5.0.4
    SHELL
  end
  
  config.vm.define "windows" do |config|
    config.vm.hostname = "windows"
#    config.vm.box      = "StefanScherer/windows_10"
    config.vm.box      = "windows_10"

    ["vmware_fusion", "vmware_workstation"].each do |provider|
      config.vm.provider provider do |v, override|
        v.gui                    = true
        v.memory                 = 4096
        v.cpus                   = 2
        v.enable_vmrun_ip_lookup = false
        v.linked_clone           = true
        v.vmx["vhv.enable"]      = "TRUE"
        v.ssh_info_public        = true
      end
    end

    config.vm.provision "shell", inline: <<-SHELL
      iwr -useb https://chocolatey.org/install.ps1 | iex
      choco install -y vagrant -version 2.0.1
      choco install -y vmwareworkstation -version 14.1.1
      $env:PATH="$env:PATH;C:\HashiCorp\Vagrant\bin"
      vagrant plugin install vagrant-vmware-workstation --plugin-version 5.0.4
    SHELL
  end  
end