# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "testbox" do |cfg|
    cfg.ssh.forward_agent = true
    cfg.vm.hostname = "testbox"
    cfg.vm.provision "shell", path: "hello.sh"

    cfg.vm.provider :digital_ocean do |provider, override|
      override.ssh.private_key_path = "~/.ssh/digitalocean_rsa"
      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      override.nfs.functional = false

      provider.token = ENV['DIGITAL_OCEAN_TOKEN']
      provider.image = 'ubuntu-16-04-x64'
      provider.region = 'fra1'
      provider.size = '1gb'
    end
  end

end
