# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.guest = :windows
  config.windows.halt_timeout = 25
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.define "multilang" do |multilang|
    multilang.vm.box = "win7x64en-enterprise"
    multilang.vm.box_url = "file:///e:/basebox/win7x64en-enterprise.box"
    multilang.vm.network :private_network, ip: "192.168.33.12", gateway: "192.168.33.1"
    multilang.vm.provision "shell", path: "shell/multilingual.cmd"
    multilang.winrm.port = 59812
    multilang.vm.network :forwarded_port, guest: 5985, host: 59812

    multilang.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
      vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'hda'] # choices: hda sb16 ac97
      vb.customize ["modifyvm", :id, '--usb', 'on', '--usbehci', 'off']
    end
  end

  config.vm.define "vs2012win81" do |vs2012win81|
    vs2012win81.vm.box = "win81x64en-eval"
    vs2012win81.vm.box_url = "file:///e:/basebox/win81x64en-eval.box"
    vs2012win81.vm.network :private_network, ip: "192.168.33.13", gateway: "192.168.33.1"
    vs2012win81.vm.provision "shell", path: "shell/main.cmd"
    vs2012win81.winrm.port = 59813
    vs2012win81.vm.network :forwarded_port, guest: 5985, host: 59813

     vs2012win81.vm.provider :virtualbox do |vb|
       vb.gui = true
       vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
       vb.customize ["modifyvm", :id, "--vram", "32"]
       vb.customize ["setextradata", :id, "CustomVideoMode1", "1680x1024x32"]
     end
  end

  config.vm.define "vs2012win7", primary: true do |vs2012win7|
    vs2012win7.vm.box = "win81x64en-eval"
    vs2012win7.vm.box_url = "file:///e:/basebox/win81x64en-eval.box"
    vs2012win7.vm.network :private_network, ip: "192.168.33.11", gateway: "192.168.33.1"
    vs2012win7.vm.provision "shell", path: "shell/main.cmd"
    vs2012win7.winrm.port = 59813
    vs2012win7.vm.network :forwarded_port, guest: 5985, host: 59813

     vs2012win7.vm.provider :virtualbox do |vb|
       vb.gui = true
       vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
       vb.customize ["modifyvm", :id, "--vram", "32"]
     end
  end

  config.vm.define "testwin7x64" do |testwin7x64|
    testwin7x64.vm.box = "win7x64en-enterprise"
    testwin7x64.vm.box_url = "file:///e:/basebox/win7x64en-enterprise.box"
    testwin7x64.vm.network :private_network, ip: "192.168.33.70", gateway: "192.168.33.1"
    testwin7x64.vm.provision "shell", path: "shell/test.cmd"
    testwin7x64.winrm.port = 59867
    testwin7x64.vm.network :forwarded_port, guest: 5985, host: 59867

    testwin7x64.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "768"]
    end
  end

  config.vm.define "testwin81x64" do |testwin81x64|
    testwin81x64.vm.box = "win81x64en-eval"
    testwin81x64.vm.box_url = "file:///e:/basebox/win81x64en-eval.box"
    testwin81x64.vm.network :private_network, ip: "192.168.33.81", gateway: "192.168.33.1"
    testwin81x64.vm.provision "shell", path: "shell/test.cmd"
    testwin81x64.winrm.port = 59881
    testwin81x64.vm.network :forwarded_port, guest: 5985, host: 59881

    testwin81x64.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1680x1024x32"]
    end
  end

end
