# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "vs2012", primary: true do |vs2012|
    vs2012.vm.communicator = "winrm"
    vs2012.vm.box = "windows_7"
    vs2012.vm.network :private_network, ip: "192.168.33.11", gateway: "192.168.33.1"
    vs2012.vm.provision "shell", path: "shell/main.cmd"

    ["virtualbox", "vmware_fusion", "vmware_workstation"].each do |provider|
      vs2012.vm.provider provider do |v, override|
        v.gui = true
        v.memory = "1536"
        v.cpus= "2"
      end
    end
    vs2012.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--vcpenabled", "off"]
      vb.customize ["modifyvm", :id, "--vcpfile", "vs0212.webm"]
    end
  end

  config.vm.define "multilang" do |multilang|
    multilang.vm.communicator = "winrm"
    multilang.vm.box = "windows_7"
    multilang.vm.network :private_network, ip: "192.168.33.12", gateway: "192.168.33.1"
    multilang.vm.provision "shell", path: "shell/multilingual.cmd"
    multilang.vm.provision "shell", path: "shell/test.cmd"

    ["virtualbox", "vmware_fusion", "vmware_workstation"].each do |provider|
      multilang.vm.provider provider do |v, override|
        v.gui = true
        v.memory = "768"
        v.cpus= "1"
      end
    end
    multilang.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, '--audio', 'dsound', '--audiocontroller', 'hda'] # choices: hda sb16 ac97
      vb.customize ["modifyvm", :id, '--usb', 'on', '--usbehci', 'off']
    end
  end

  config.vm.define "p50" do |p50|
    p50.vm.box = "ubuntu1404"
    p50.vm.network :private_network, ip: "192.168.33.50", gateway: "192.168.33.1"
    p50.vm.provision "shell", path: "shell/p50.sh"

    ["virtualbox", "vmware_fusion", "vmware_workstation"].each do |provider|
      p50.vm.provider provider do |v, override|
        v.memory = "1024"
        v.cpus= "1"
      end
    end
  end
end
